import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

export const metadata = {
  title: "Welcome to Dor | Terms Of Use",
  description: "Your doorway to unlimited entertainment.",
};

const TermsOfUse = () => {
  return (
    <div className="relative bg-gray-900">
      <Navbar alwaysOnTop={true} />
      <div className="flex justify-center">
        <div className="w-[1184px] mt-[110px] mb-[148px] px-8">
          <p className="text-gray-50 text-[14px]">
            <span className="text-gray-600 ">Support / </span>Terms of Use
          </p>
          <h2 className="mt-[20px] text-[30px] font-neue-medium leading-[38px] text-gray-50 font-semibold">
            Terms of Use
          </h2>
          <p className="mt-10 text-gray-400 text-[14px] font-normal">
            These Terms of Use (&quot;Terms&quot;) govern your use of DOR
            Service via DOR TV and DOR App. By accessing or using DOR Service,
            you agree to be bound by these Terms and the{" "}
            <span className="text-gray-50">Privacy Policy</span> (collectively
            referred to as “User Agreement”).
          </p>
          <p className="mt-2 text-gray-400 text-[14px] font-normal">
            In this User Agreement, the following terms shall have the meaning
            as ascribed to them below:
          </p>
          <p className="mt-2 text-gray-400 text-[14px] font-normal">
            “DOR Service” means an on-demand video subscription service
            currently titled ‘DOR’ that enables you discover and view contents
            across various OTT Apps with single sign-on interface and single
            billing.
          </p>
          <div className="grid gap-5 mt-2">
            <p className="text-gray-400 text-[14px] font-normal">
              a. “DOR Service” means an on-demand video subscription service
              currently titled ‘DOR’ that enables you discover and view contents
              across various OTT Apps with single sign-on interface and single
              billing.
            </p>
            <p className="text-gray-400 text-[14px] font-normal">
              b. “DOR TV” means our Smart TV, which has an inbuilt DOR operating
              system, without which DOR Service cannot be accessed and/or used.
            </p>
            <p className="text-gray-400 text-[14px] font-normal">
              c. “DOR App” means our companion mobile application, where DOR
              Service may be accessed and used on complementary basis provided
              you have subscribed to DOR Service on DOR TV.
            </p>
            <p className="text-gray-400 text-[14px] font-normal">
              d. “DOR Store” means the application store from where you can
              separately subscribe to OTT Apps not forming part of the DOR
              Service upon payment of additional subscription fees. 
            </p>
          </div>
          <div className="grid gap-5 mt-2">
            <p className="text-gray-400 text-[14px] font-normal">
              DOR Service, DOR TV, DOR App and DOR Store are owned and/or
              operated by Streambox Media Private Limited, a company
              incorporated under the laws of India, having its registered office
              at 21/14, Block-A, Ph-2, Naraina Industrial Estate, New Delhi –
              110028 and corporate office at K Raheja Platinum, Office no.
              6B-115, Marol Industrial Estate, Andheri East, Mumbai – 400059
              (“Streambox”).
            </p>
            <p className="text-gray-400 text-[14px] font-normal">
              This User Agreement is an electronic record in accordance with the
              Information Technology Act, 2000 and rules thereunder, as
              applicable and the amended provisions pertaining to electronic
              records in various statutes as amended by the Information
              Technology (Amendment) Act, 2008, and such other applicable
              amendments, from time to time. This User Agreement is generated by
              a computer system and does not require any physical or
              electronic/digital signatures.
            </p>
          </div>
          <p className="mt-2 text-gray-400 text-[14px] font-normal">
            Please read the User Agreement carefully before accessing,
            installing or using DOR Service. If you do not agree to the
            provisions of the User Agreement, please do not use DOR Service and
            forthwith return DOR TV to Streambox. Any use of DOR Service
            thereafter will be deemed unauthorised.
          </p>
          <div className="grid gap-5 mt-5">
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                1. Introduction
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                Streambox provides DOR Service only in India via DOR TV and DOR
                App. While DOR TV is provided by Streambox upon receipt of a
                security deposit, access to DOR Service via DOR TV requires
                payment of subscription fees, which includes complimentary
                access of DOR Service via DOR App.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                2. Eligibility
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                DOR Service is available to individual residing in India, who is
                at least 18 years of age (fully competent under law to enter
                into an agreement) (or above 21 years of age, where a guardian
                is appointed as per the Majority Act of 1875) (“Age of
                Majority”). By using DOR Service, you represent and warrant that
                you meet this requirement. If you are under the Age of Majority
                at the time of accessing and/or using the Service, your access
                and usage of DOR Service will be deemed to be subject to
                parental/legal guardian consent and under parental/legal
                guardian’s guidance at all times. Under such circumstances, this
                User Agreement will constitute a legally binding agreement
                between Streambox and your parents/guardians, who are
                contracting on your behalf.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                3. Subscription Fees for DOR Service
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                In order to access DOR Service via DOR TV, you need to subscribe
                to DOR Service and make payments towards subscription fees on
                regular intervals. Streambox reserves the right to change the
                subscription fees and/or offer new subscription plans from time
                to time. Till such time the subscription of DOR Service is
                active on DOR TV, your access to DOR Service via DOR App will be
                complementary.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                4. Subscription Fees for other OTT Apps
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                In order to access other OTT Apps, not forming part of DOR
                Service, via DOR TV on a-la-carte basis, you may separately
                subscribe to such OTT Apps on DOR Store and make separate
                payments towards subscription fees on regular intervals. The
                subscription fees for such OTT apps are determined by their
                respective owners and/or operators and Streambox has no say on
                such subscription fees. Till such time the subscription of such
                Apps are active on DOR TV, your access to such Apps via DOR App
                will be complementary.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                5. Security Deposit for DOR TV
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                DOR TV is not sold but is made available to you by Streambox
                upon payment of a nominal security deposit. The security deposit
                payable depends on the size of DOR TV opted by you. Streambox
                reserves the right to change the security deposit of existing
                sizes DOR TVs and/or introduce new security deposits for bigger
                or smaller or same size DOR TVs from time to time. Any time
                after one (1) year from DOR TV installation date, you may return
                your DOR TV to Streambox or upgrade to a bigger size DOR TV if
                available. It is clarified that within one (1) year from your
                DOR TV installation date, you can neither return your DOR TV nor
                upgrade/downgrade to a bigger/smaller size DOR TV. If you return
                your DOR TV to Streambox after one (1) year from your DOR TV
                installation date, Streambox will refund the security deposit to
                you subject to applicable deductions towards damages (to be
                solely determined by Streambox) and outstanding fees, within one
                (1) month from the date of return of your DOR TV. If you upgrade
                to a bigger size DOR TV after one (1) year from your DOR TV
                installation date, you will have to pay additional security
                deposit to Streambox as per available schemes.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                6. Purchase of DOR Service subscriptions
              </h2>
              <p className="mt-2 text-[14px] font-normal text-gray-400">
                DOR Service may be subscribed via our website (www.dorworld.in)
                or DOR App or on the website and App of our third party vendor
                upon payment of applicable subscription fees and security
                deposit. While making such payments, you are required to provide
                your personal and payment information to enable Streambox or its
                authorized vendor raise the invoice and organize installation of
                DOR TV at the address specified by you.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                7. Installation & Demonstration of DOR TV
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                Streambox provides complementary services for installation of
                DOR TV. Subject to receipt of the subscription fees and security
                deposit from you, Streambox will endeavour to schedule
                installation and demonstration of DOR TV at the installation
                address provided by you within two (2) days (if within
                municipal/town limits) and three (3) days (if outside
                municipal/town limits) from the purchase of DOR Service
                subscription at a mutually agreed time. It is your
                responsibility to ensure that the installation site meets all
                technical specifications and requirements. You agree to provide
                our technicians with reasonable access to your premises to
                perform such installation. Any additional installation
                requirements or custom setup beyond the standard installation
                may incur additional charges, which will be communicated to you
                beforehand. Any change in location during the Warranty Period
                must be intimated by the User to Streambox in writing.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                8. Registration & Activation of DOR Service
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                To access DOR Service, you need to create an account via DOR TV
                by using your mobile number and the OTP generated on such mobile
                number. It is made abundantly clear that your subscription of
                DOR service is linked to your mobile number and it is critical
                that you maintain the same mobile number during the validity of
                DOR service subscription. Any change in mobile number will
                warrant payment of new subscription fees and security deposit.
                You agree to accept responsibility for all activities that occur
                under your account. Your account will be activated and your
                billing cycle will commence the day you are able to access DOR
                Service on DOR TV.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                9. Use of DOR Service
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                DOR Service gives you access to multiple OTT Apps. Streambox
                reserves the right to add or delete OTT Apps from DOR Service
                without changing subscription fees payable by you. DOR Service
                is provided to you for personal, non-commercial use only in
                India. In order to receive an uninterrupted DOR Service, you
                have to ensure that you have supply of incidental accessories
                and services, including internet service and power supply. In
                order to access, DOR Service on DOR App, you need to download
                DOR Application from DOR Store (ios & android) or App Store
                (ios) or Play Store (android) on your mobile device. Your mobile
                device must be compatible with DOR App and must meet the
                necessary technical requirements. You agree to use DOR Service
                in compliance with all applicable laws and regulations. In
                addition to compliance of the User Agreement, you also agree to
                review and comply with the terms of use and privacy policy of
                all OTT Apps forming part of DOR Service. 
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                10. DOR TV Warranty
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                Subject to your use of DOR TV in the manner specified in the
                instruction manual provided with DOR TV and your continued
                subscription of DOR Service, DOR TV is warranted against defects
                in materials and workmanship under normal use for a period of
                four (4) years from DOR TV Installation date. During the
                warranty period, if a defect arises and a valid claim is made by
                you, Streambox will, at its option, either repair DOR TV at its
                own cost or exchange DOR TV with a same sized new or refurbished
                DOR TV. Such warranty will only cover manufacture defects
                (including faulty components or assembly errors, etc.),
                mechanical/electronic breakdowns (including power supply,
                malfunctioning circuitry or panel defects, etc.), parts and
                labour. It is clarified that such warranty will not cover
                unauthorised modifications i.e., alterations without
                manufacturer approval etc., cosmetic damages, accidental damages
                including but not limited to misuse, mishandling, physical
                impact, liquid spill etc. The warranty is not transferable and
                non-assignable. To make a warranty claim, please contact our
                customer service team at (+91) 9088360360 any time between 10 am
                to 6 pm on all working days, except Sundays and twelve (12)
                holidays in the year, as determined by Streambox. Our customer
                service team have proficiency in English and Hindi languages.
                You need to provide proof of delivery of such DOR TV, proof of
                continued DOR Service subscription, describe the problem in
                detail, and follow any further instructions provided by our
                customer service team. If complaint lodged before 1 pm, subject
                to validation of such compliant by Streambox, Streambox will
                endeavour to address the complaint within two (2) days (if
                within municipal/town limits) and three (3) days (if outside
                municipal/town limits). 
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                11. Suspension & Deactivation 
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                Streambox reserves the right to suspend or deactivate your DOR
                Service account for any reason whatsoever, including your
                failure to comply with this User Agreement and/or the terms of
                use and privacy policy of all OTT Apps forming part of DOR
                Service, non-payment of subscription fees and/or the security
                deposit or making unauthorised use of DOR Service. In addition
                to such suspension or deactivation, Streambox will have the
                right to exercise all other rights and remedies available to
                Streambox against you under applicable laws. Upon deactivation
                of DOR Service, you will forthwith return your DOR TV to
                Streambox and Streambox will refund the security deposit to you
                subject to applicable deductions towards damages (to be solely
                determined by Streambox) and outstanding fees, within one (1)
                month from the receipt of your DOR TV. You will not claim any
                interest, charge or lien on the DOR TV, even if any dispute is
                pending for resolution between you and Streambox. 
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                12. Intellectual Property
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                The contents available on DOR Service are protected by
                copyright, trademark and other intellectual property laws. You
                will not reproduce, modify, create derivative works based on
                such contents or publicly display any content from DOR Service.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                13. Content Disclaimer
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                As mentioned above, DOR Service merely aggregates and
                distributes contents of various third party OTT operators.
                Streambox does not have any control over the contents available
                on DOR Service. Each OTT reporter is solely responsible for the
                content they provide, including its classification, descriptions
                and any other related information. Streambox does not endorse or
                assume responsibility for accuracy, legality or quality of such
                content.  If you wish to register any complaint with respect to
                the content of any such OTT operators, kindly reach out to our
                Grievance Officer, [●] at contentgrievance@dorworld.in. Please
                ensure that your e-mail clearly states (i) your name, (ii) name
                of the OTT operator, show/programme, and series/episode number,
                and (iii) details of the complaint. Streambox will acknowledge
                your e-mail in 24 hours and get your complaint addressed with
                fifteen (15) days. Streambox will direct the complaint to the
                OTT operator responsible for the content and facilitate
                redressal. Alternately, you may wish to directly register the
                complaint with the grievance officer of the OTT operator
                responsible for such content.   
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                14. Disclaimer & Limitation of Liability
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                DOR Service is provided ‘as is’ without warranties of any kind.
                Streambox does not guarantee the accuracy, reliability or
                availably of DOR Service (including the contents and services of
                third party OTT Apps forming part of DOR Service). Streambox and
                its affiliates, officers, employees, agents, partners, and
                licensors will not be liable for any indirect, incidental,
                special, consequential, or punitive damages, including without
                limitation, loss of profits, data, use, goodwill, or other
                intangible losses, resulting from (i) your use or inability to
                use DOR Service; (ii) unauthorized access to or alteration of
                your transmissions or data; or (iii) any other matter related to
                DOR Service. Streambox is not liable for any incidental or
                consequential damages resulting from the use of DOR TV.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50 ">
                15. Miscellaneous
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(a) Confidentiality:</span>{" "}
                Neither you nor any person through you shall disclose or make
                available to any third party any information relating to the
                operations or the business of Streambox or its group companies,
                their affiliates, their representatives/officers. Neither you
                nor any persons related to you shall make any statements of any
                nature including without limitation statements relating to
                Streambox or its group companies, their affiliates, their
                representatives/officers or its operations, its activities, to
                any third party or the press or any media company(ies)/service.
                Violation of this obligation shall immediately result in the
                discontinuation of DOR Service. Streambox further reserves the
                right to take action against you or such other persons as deem
                fit by Streambox including initiate legal action against such
                violation of this clause.
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(b) Assignment:</span> This User
                Agreement cannot be transferred or assigned by you but may be
                delegated or assigned (in part or whole) by Streambox to any
                third party without restriction and/or consent.
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(c) Indemnity:</span> You agree
                to defend, indemnify and hold harmless Streambox its affiliates,
                its parent company, officers, directors, employees and agents,
                from and against any and all claims, damages, obligations,
                losses, liabilities, costs or debt, and expenses (including but
                not limited to attorney&apos;s fees) arising from your use of
                and access to DOR Service, your violation of any term of this
                User Agreement or any third party right, including, without
                limitation, any copyright, property, or privacy right. The
                indemnification obligation will survive the termination of this
                User Agreement or the usage of DOR Service by you.
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(d) Waiver:</span> The failure of
                Streambox to enforce any right or provision of this User
                Agreement will not be considered a waiver of those rights. 
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(e) Severability:</span> If any
                provision of this User Agreement becomes invalid, illegal or
                unenforceable, in whole or in part, the validity of the
                remainder provisions of this User Agreement will not be affected
                thereby.
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(f) Relationship:</span> This
                User Agreement is on a ‘principal to principal’ basis and the
                parties are independent of each other. Nothing contained herein
                is intended to or shall be deemed to create any partnership,
                joint venture, employment or relationship of principal and agent
                between the parties or provides either with any right, power or
                authority, whether express or implied to create any such duty or
                obligation on behalf of the other party.
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(g) Force Majeure:</span>{" "}
                Streambox shall not be responsible or liable in any way for the
                failure or delay in the performance of its obligations due to
                Force Majeure. If a Force Majeure ceases to exist, Streambox may
                perform or resume performance of its obligations and the time
                for performance will be extended by a period equal to the
                duration of the Force Majeure. Reasonable efforts shall be made
                to minimise such service disruptions. If Force Majeure persists,
                Streambox shall be entitled to terminate this User Agreement on
                written notice. You shall remain liable for all charges during
                any such disruptions, unless decided otherwise by Streambox.
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(h) Notices:</span> All
                notifications, complaints and notices must be in writing and
                addressed to Customer Operations, Streambox Media Private
                Limited, at its registered address or otherwise as specified by
                the Helpdesk. Any notification, complaints and notices given by
                you shall be deemed to have been delivered to Streambox when it
                is received by Streambox. You could also call the Helpline to
                seek information or register any complainant. Calls from your
                Registered Mobile Number(s) will be identified by the Helpline
                however identification verification may be sought. You agree to
                provide true, accurate, current and complete information about
                you and your subscription. Streambox will endeavor to handle and
                resolve all your queries and complaints through its Helpline.
                You agree that notifications provided by Streambox in such form
                as prescribed by Streambox from time to time, including
                notifications provided by the Helpdesk, Alert, Account Statement
                or any other method specified by Streambox or the Helpdesk, will
                be sufficient and adequate notice to you. 
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">
                  (i) Governing Law & Jurisdiction:
                </span>
                The rights and obligations of the Parties under this User
                Agreement shall be governed by and construed in accordance with
                the laws of India. Courts in Delhi, to the exclusion of all
                other courts, shall have exclusive jurisdiction in respect of
                any dispute between the Parties arising out of or in connection
                with or as a result of this User Agreement.
              </p>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                <span className="text-gray-50">(j) Entire Agreement:</span> This
                User Agreement contains the entire understanding between the
                Parties regarding your use of DOR Service.
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                16. Changes to the User Agreement
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                Streambox reserves the right to modify or replace the User
                Agreement at any time. If a revision is material, Streambox will
                notify you via DOR Service or by any other means. What
                constitutes a material change will be determined at sole
                discretion of Streambox. Your continued use of DOR Service after
                such changes constitutes your acceptance of the new User
                Agreement. 
              </p>
            </div>
            <div>
              <h2 className="text-[18px] leading-[28px] font-medium pl-2 text-gray-50">
                17. Contact Us
              </h2>
              <p className="mt-2 text-gray-400 text-[14px] font-normal">
                If you have any questions about the User Agreement, please
                contact us at{" "}
                <span className="text-gray-50">contact@dorworld.in</span>.
              </p>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default TermsOfUse;
