import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",  weight: "100 900",
});

const neueHaasMedium = localFont({
  src: "./fonts/NeueHaasDisplayMediu.ttf",
  variable: "--font-neuehaas-medium",
  weight: "600",
});

const neueHaasLight = localFont({
  src: "./fonts/NeueHaasDisplayLight.ttf",
  variable: "--font-neuehaas-light",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${neueHaasMedium.variable} antialiased font-geist`}
      >
        {children}
      </body>
    </html>
  );
}
